# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3.9'
# Define services
services:
  keycloak:
    container_name: keycloak-auth
    image: quay.io/keycloak/keycloak:latest
      #build:
      # context: .
    #args:
    # KEYCLOAK_VERSION: 22.0.1
    command:
      - "start-dev"
    ports:
      - "8180:8080"
    networks:
      - keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HEALTH_ENABLED: true
    depends_on:
      - keycloak-db
    #volumes:
    #  - /home/keycloak/automobile-realm.json:/opt/keycloak/data/import/automobile-realm.json
  # Database Service (Postgres) for Keycloak
  keycloak-db:
    image: postgres:15-alpine
    container_name: keycloak-db
    hostname: 'keycloak-db'
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_keycloak:/var/lib/postgresql/data
    environment:
      - TZ=GMT+7
      - PGTZ=GMT+7
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=keycloak
    networks: [ keycloak ]
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U" ]
      timeout: 45s
      interval: 10s
      retries: 10


  devdb:
    image: 'postgres:15'
    container_name: 'devdb'
    hostname: 'devdb'
    environment:
      - TZ=GMT+7
      - PGTZ=GMT+7
      - POSTGRES_USER=devkh
      - POSTGRES_PASSWORD=devKH@2023
      - POSTGRES_DB=dev_kh
    ports:
      - '5451:5432'
    volumes:
      - keycloak_db_vol:/var/lib/postgresql/data/
    restart: always
    networks:
      - devkh_micro_net


networks:
  # backend:
  #  name: app
  # driver: bridge
  keycloak:
    name: keycloak
    driver: bridge
  devkh_micro_net:
    external: true
    name: devkh_micro_net
volumes:
  keycloak_db_vol:
  keycloak_data:
  postgres_data_keycloak:
    driver: local

# version: '3.8'

# services:

#   keycloak:
#     image: quay.io/keycloak/keycloak:latest
#     ports:
#       - "8180:8080"
#     environment:
#       KEYCLOAK_ADMIN: admin
#       KEYCLOAK_ADMIN_PASSWORD: admin
#     command:
#       - start-dev
#       - --import-realm
#     volumes:
#       - ./config/keycloak-realm.json:/opt/keycloak/data/import/realm.json
