server:
    port: 9080
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: devKH@2023
        url: jdbc:postgresql://localhost:5451/dev_Keycloak
        username: devkh
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                show_sql: true
    profiles:
        active: '[dev]'
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8280/realms/dev-keycloak
keycloak:
    realm: dev-keycloak
    domain: localhost:8280
    adminClientId: admin-cli
    adminClientSecret: TzfTf6Tzb48qsc0YI1lfiJZLwQtf3wgk
    client: admin-cli
    urls:
        auth: http://${keycloak.domain}
